apiVersion: v1
kind: Secret
metadata:
    name: admin-login-secrets
    namespace: giftcardsite
type: Opaque
data:
    username: YWRtaW4=
    password: dGhpc2lzYXRlc3R0aGluZy4=
    mysql_root_password: dGhpc2lzYXRlc3R0aGluZy4=