kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  namespace: giftcardsite
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/mysql-pv
